---

- name: transfer certificate file
  delegate_to: localhost
  become: no
  command:
    cmd: scp "{{ certificate }}"  {{ inventory_hostname }}:"{{ unifi_certificate_path }}/unifi-core.crt"

- name: transfer certificate key
  delegate_to: localhost
  become: no
  command:
    cmd: scp "{{ certificate_key }}" {{ inventory_hostname }}:{{ unifi_certificate_path }}/unifi-core.key

- name: reload certificates into unifi-os
  raw: podman exec -it {{ unifi_os_container }} \
        {{ java_certificate_import }} \
        {{ unifi_os_certificate_path }}/unifi-core.key \
        {{ unifi_os_certificate_path }}/unifi-core.crt

- name: restart unifi-os
  raw: unifi-os restart
