---

- name: user defined certificate
  include_tasks: certificate.yml
  when: certificate is defined

- name: deploy onboot
  include_tasks: onboot.yml

- name: deploy udm-kernel-tools
  when: install_kernel_tools
  include_tasks: kernel-tools.yml
